### ISSUE TITLE
Bytelandian Gold Coin-Codechef

### ISSUE THREAD

**Issue by bagofcodes** [chandrikadeb7/Hacktoberfest_2020#117]
I would like to submit my Solution for the competitive coding task @chandrikadeb7

**Comment by bagofcodes** [comment]
Submitted the PR for the solution of the same kindly review it @chandrikadeb7

**Comment by bagofcodes** [comment]
Would like to add another codechef question Covid Pandemic and Long queue solution which was in the April Long Challenge 2020

**Comment by nimishbongale** [comment]
@bagofcodes 

You can submit as many PR's as you wish really. This repo will continue accepting hacktoberfest contributions for newbies.

I'm going to go ahead and close this issue. You can directly raise a PR if you wish!
